# Generated by Django 5.0 on 2026-04-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('license_plate', models.CharField(max_length=15, unique=True, verbose_name='Госномер')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день')),
                ('car_type', models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('suv', 'Внедорожник'), ('premium', 'Премиум')], max_length=20, verbose_name='Тип')),
                ('transmission', models.CharField(choices=[('manual', 'Механика'), ('auto', 'Автомат')], max_length=10, verbose_name='Коробка')),
                ('seats', models.IntegerField(default=4, verbose_name='Кол-во мест')),
                ('fuel_type', models.CharField(default='petrol', max_length=20, verbose_name='Топливо')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
